// Code generated by protoc-gen-go.
// source: claw/motor/motor.proto
// DO NOT EDIT!

/*
Package motor is a generated protocol buffer package.

It is generated from these files:
	claw/motor/motor.proto

It has these top-level messages:
*/
package motor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State int32

const (
	State_STOPPED  State = 0
	State_FORWARD  State = 1
	State_BACKWARD State = 2
)

var State_name = map[int32]string{
	0: "STOPPED",
	1: "FORWARD",
	2: "BACKWARD",
}
var State_value = map[string]int32{
	"STOPPED":  0,
	"FORWARD":  1,
	"BACKWARD": 2,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("motor.State", State_name, State_value)
}

func init() { proto.RegisterFile("claw/motor/motor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0xce, 0x49, 0x2c,
	0xd7, 0xcf, 0xcd, 0x2f, 0xc9, 0x2f, 0x82, 0x90, 0x7a, 0x05, 0x45, 0x40, 0x4a, 0x88, 0x15, 0xcc,
	0xd1, 0xd2, 0xe7, 0x62, 0x0d, 0x2e, 0x49, 0x2c, 0x49, 0x15, 0xe2, 0xe6, 0x62, 0x0f, 0x0e, 0xf1,
	0x0f, 0x08, 0x70, 0x75, 0x11, 0x60, 0x00, 0x71, 0xdc, 0xfc, 0x83, 0xc2, 0x1d, 0x83, 0x5c, 0x04,
	0x18, 0x85, 0x78, 0xb8, 0x38, 0x9c, 0x1c, 0x9d, 0xbd, 0xc1, 0x3c, 0xa6, 0x24, 0x36, 0xb0, 0x76,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x44, 0x39, 0x37, 0x58, 0x00, 0x00, 0x00,
}
